// build-sprites.ts - Compile individual images into sprite sheet with JSON atlas

import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import { packAsync } from 'free-tex-packer-core';

const SOURCE_DIR = 'sprites-source';
const OUTPUT_DIR = 'public/assets/sprites';
const HASH_FILE = 'src/game/spriteHash.ts';

async function main() {
  console.log('Building sprite sheet...\n');

  // Ensure output directory exists
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });

  // Clean up old hashed sprite files
  const existingFiles = fs.readdirSync(OUTPUT_DIR);
  for (const file of existingFiles) {
    if (file.match(/^items\.[a-f0-9]+\.(png|json)$/)) {
      fs.unlinkSync(path.join(OUTPUT_DIR, file));
      console.log(`  Removed old: ${file}`);
    }
  }

  // Read all PNG files from source directory
  console.log('Loading source images...');
  const images: { path: string; contents: Buffer }[] = [];

  const files = fs.readdirSync(SOURCE_DIR).filter(f => f.endsWith('.png'));

  for (const file of files) {
    const sourcePath = path.join(SOURCE_DIR, file);
    console.log(`  ${file}`);
    images.push({
      path: file,
      contents: fs.readFileSync(sourcePath),
    });
  }

  if (images.length === 0) {
    console.error('No images found. Exiting.');
    process.exit(1);
  }

  console.log(`\nPacking ${images.length} sprites into sheet...`);

  // Pack sprites into sheet
  const packResult = await packAsync(images, {
    textureName: 'items',
    width: 1024,
    height: 1024,
    fixedSize: false,
    powerOfTwo: true,
    padding: 1,
    allowRotation: false,
    allowTrim: false,
    exporter: 'JsonHash',
    removeFileExtension: true,
  });

  // Generate content hash from the PNG data
  const pngFile = packResult.find(f => f.name.endsWith('.png'));
  if (!pngFile) {
    console.error('No PNG output found');
    process.exit(1);
  }
  const hash = crypto.createHash('md5').update(pngFile.buffer).digest('hex').slice(0, 8);
  console.log(`\nContent hash: ${hash}`);

  // Write output files with hash in filename
  for (const file of packResult) {
    const ext = path.extname(file.name);
    const hashedName = `items.${hash}${ext}`;
    const outputPath = path.join(OUTPUT_DIR, hashedName);
    fs.writeFileSync(outputPath, file.buffer);
    console.log(`  Written: ${outputPath}`);
  }

  // Generate TypeScript file with hash
  const tsContent = `// Auto-generated by build-sprites.ts - do not edit
export const SPRITE_HASH = '${hash}';
`;
  fs.writeFileSync(HASH_FILE, tsContent);
  console.log(`  Written: ${HASH_FILE}`);

  console.log('\nSprite sheet build complete!');
}

main().catch((error) => {
  console.error('Build failed:', error);
  process.exit(1);
});
